name: .NET Release on tag push

env:
  PUB_DIR_NAME: DnfServerSwitcher
  CUR_PROJ: ./DnfServerSwitcher/DnfServerSwitcher.csproj
  PUB_PATH: ./publish/DnfServerSwitcher

on:
  push:
    tags:
      - "V*.*.*"

jobs:
  publish_and_release:

    runs-on: windows-latest

    steps:
      # ---- Checkout main source code
      - name: Checkout
        uses: actions/checkout@v3
      
      # ---- CSPROJ Version preparations
      - name: Get csproj version
        uses: kzrnm/get-net-sdk-project-versions-action@v1
        id: get-version
        with:
          proj-path: ${{env.CUR_PROJ}}
      
      
      # ---- .NET Preparations
      - name: Restore dependencies
        run: dotnet restore ${{env.CUR_PROJ}}
      
      
      # ---- Publish and archive - net462 Windows x86
      - name: Publish net462 win-x86
        run: dotnet publish ${{env.CUR_PROJ}} --output ./publish/net462_win-x86/${{env.PUB_DIR_NAME}}/ --configuration Release --framework net462 --runtime win-x86 -p:Platform=x86
      - name: Archive published net462 win-x86
        uses: ihiroky/archive-action@v1
        with:
          root_dir: "./publish/net462_win-x86/"
          file_path: "${{env.PUB_PATH}}_V${{steps.get-version.outputs.version}}_net462_win-x86.zip"
      
      
      
      # ---- Publish and archive - net462 Windows x64

      - name: Publish net462 win-x64
        run:  dotnet publish ${{env.CUR_PROJ}} --output ./publish/net462_win-x64/${{env.PUB_DIR_NAME}}/ --configuration Release --framework net462 --runtime win-x64 -p:Platform=x64
      - name: Archive published net462 win-x64
        uses: ihiroky/archive-action@v1
        with:
          root_dir: "./publish/net462_win-x64/"
          file_path: "${{env.PUB_PATH}}_V${{steps.get-version.outputs.version}}_net462_win-x64.zip"
      
      
      # ---- Creating github Release

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "Automatic release for version V${{steps.get-version.outputs.version}}"
          token: ${{github.token}}
          repository: ${{github.repository}}
          files: |
            ${{env.PUB_PATH}}_V${{steps.get-version.outputs.version}}_net462_win-x86.zip
            ${{env.PUB_PATH}}_V${{steps.get-version.outputs.version}}_net462_win-x64.zip

